hello_world: hello_world.o input_num.o 
	g++ -o hello_world hello_world.o
	g++ -o input_num input_num.o
	g++ -c input_num.cc
	g++ -c hello_world.cc
clean:
	rm hello_world input_num hello_world.o input_num.o

